name: CI
on: push
env: 
  APP_name: my-app
jobs: 
  build:
   runs-on: ubuntu-latest
   env:
    NODE_ENV: production
   steps:
    - name: Show them
      env:
       GREETING: hello
      run: echo "SAPP_NAME $NODE_ENV $GREETING"


