name: new

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello! My GitHub Actions workflow is working!"

      - name: Show Date
        run: date
